services:
  vllm:
    image: vllm/vllm-openai:v0.13.0
    environment:
      - HF_HUB_OFFLINE=1
      - NVIDIA_VISIBLE_DEVICES=all
      - HF_TOKEN=${HF_TOKEN}
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8000:8000"
    command: >
      cyankiwi/Qwen3-VL-8B-Instruct-AWQ-4bit
      --served-model-name qwen3-VL-8B
      --limit-mm-per-prompt.video 0
      --async-scheduling
      --max-num-seqs 128
      --max-model-len 32K
      --gpu-memory-utilization 0.8
      --enable-chunked-prefill
      --kv_cache_dtype "fp8"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        
  backend:
        build:
                context : ./src/backend
                dockerfile : ./Dockerfile
        ports:
                - "8080:8080"
        environment:
                - VLLM_URL=http://vllm:8000/v1
        volumes:
                - ./src/backend:/app
        depends_on:
                - vllm